/*
 * (C) Copyright 2007-2009 Michal Simek
 * Michal SIMEK <monstr@monstr.eu>
 *
 * (C) Copyright 2010-2012 Li-Pro.Net
 * Stephan Linz <linz@li-pro.net>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 * MA 02111-1307 USA
 *
 * CAUTION:  This file is automatically generated by libgen.
 * Version:  Xilinx EDK 13.2 EDK_O.61xd
 * Today is: Wednesday, the 20 of June, 2012; 20:33:09
 *
 * Description: U-Boot Configurations
 *
 * Generate by uboot-v4.02.a
 * Project description at http://www.monstr.eu/
 */

/* Project name */
#define XILINX_BOARD_NAME	"Avnet-S6LX9-AXI-tiny-13.2"

/* Microblaze is microblaze_0 */
#define XILINX_USE_MSR_INSTR                     0
#define XILINX_PVR                               0
#define XILINX_FSL_NUMBER                        0
#define XILINX_USE_ICACHE                        1
#define XILINX_USE_DCACHE                        1
#define XILINX_DCACHE_BYTE_SIZE                  8192

/* Interrupt controller is axi_intc_0 */
#define XILINX_INTC_BASEADDR                     0x41200000
#define XILINX_INTC_NUM_INTR_INPUTS              5
/* axi_uart_0_Interrupt */
/* axi_gpio_3_IP2INTC_Irpt */
/* axi_spi_0_IP2INTC_Irpt */
/* axi_ether_0_IP2INTC_Irpt */
/* axi_timer_0_Interrupt */

/* System (Timer) Clock Frequency */
#define XILINX_CLOCK_FREQ                        66666666

/* Timer is axi_timer_0 */
#define XILINX_TIMER_BASEADDR                    0x41c00000
#define XILINX_TIMER_IRQ                         0

/* System memory is axi_s6_ddrx_0 */
#define XILINX_RAM_START                         0x80000000
#define XILINX_RAM_SIZE                          0x04000000

/* NOR Flash memory not defined */

/* Uart controller UARTLITE 0 is axi_uart_0 */
#define XILINX_UARTLITE                         
#define XILINX_UARTLITE_BASEADDR                 0x40600000
#define XILINX_UARTLITE_BAUDRATE                 115200

/* I2C controller not defined */

/* GPIO controller is axi_gpio_3 */
#define XILINX_GPIO_BASEADDR                     0x40000000

/* Sysace CF controller not defined */

/* Ethernet MAC controller EMACLITE is axi_ether_0 */
#define XILINX_EMACLITE                         
#define XILINX_EMACLITE_BASEADDR                 0x40e00000

